/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Ozmond
 */
public class PenilaianKaryawan extends javax.swing.JFrame {
    Connection conn;
    Statement stm;
    ResultSet rs;
    /**
     * Creates new form HalamanUtama
     */
    public PenilaianKaryawan() {
        initComponents();
        tbl_penilaian();
        kosong();
        autoAlternatif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_halamanutama = new javax.swing.JButton();
        btn_datakaryawan = new javax.swing.JButton();
        btn_databobot = new javax.swing.JButton();
        btn_penilaiankaryawan = new javax.swing.JButton();
        btn_prosesdata = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txt_idKaryawan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_alternatif = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_c2 = new javax.swing.JComboBox<>();
        cb_c3 = new javax.swing.JComboBox<>();
        cb_c4 = new javax.swing.JComboBox<>();
        btn_laporan = new javax.swing.JButton();
        cb_c1 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_penilaian = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 62, 70));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Penilaian Karyawan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
        );

        jPanel2.setBackground(new java.awt.Color(0, 173, 181));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/menu30.png"))); // NOI18N
        jLabel1.setText("Menu");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        btn_halamanutama.setBackground(new java.awt.Color(250, 250, 250));
        btn_halamanutama.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_halamanutama.setText("Halaman Utama");
        btn_halamanutama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_halamanutamaActionPerformed(evt);
            }
        });

        btn_datakaryawan.setBackground(new java.awt.Color(250, 250, 250));
        btn_datakaryawan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_datakaryawan.setText("Data Karyawan");
        btn_datakaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datakaryawanActionPerformed(evt);
            }
        });

        btn_databobot.setBackground(new java.awt.Color(250, 250, 250));
        btn_databobot.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_databobot.setText("Data Bobot");
        btn_databobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_databobotActionPerformed(evt);
            }
        });

        btn_penilaiankaryawan.setBackground(new java.awt.Color(170, 170, 170));
        btn_penilaiankaryawan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_penilaiankaryawan.setText("Penilaian Karyawan");
        btn_penilaiankaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penilaiankaryawanActionPerformed(evt);
            }
        });

        btn_prosesdata.setBackground(new java.awt.Color(250, 250, 250));
        btn_prosesdata.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_prosesdata.setText("Proses Data");
        btn_prosesdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesdataActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(250, 250, 250));
        btn_logout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_datakaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_halamanutama, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_databobot, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_penilaiankaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_prosesdata, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_halamanutama, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_datakaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_databobot, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_penilaiankaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_prosesdata, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jPanel4.setBackground(new java.awt.Color(241, 246, 249));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MASUKKAN PENILAIAN KARYAWAN");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("ID Karyawan");

        txt_idKaryawan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Nama Karyawan");

        txt_nama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_alternatif.setBackground(new java.awt.Color(204, 204, 204));
        txt_alternatif.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Alternatif");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Tingkat Kehadiran (C1)");

        btn_simpan.setBackground(new java.awt.Color(57, 62, 70));
        btn_simpan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconsave25.png"))); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_ubah.setBackground(new java.awt.Color(57, 62, 70));
        btn_ubah.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_ubah.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconedit25.png"))); // NOI18N
        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(57, 62, 70));
        btn_reset.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconclear25.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(57, 62, 70));
        btn_hapus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icondelete25.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_cari.setBackground(new java.awt.Color(57, 62, 70));
        btn_cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/search15.png"))); // NOI18N
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Tingkat Pendidikan (C2)");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Pengembangan Diri (C3)");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Unsur Penunjang (C4)");

        cb_c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Kurang Dari Persyaratan Minimal", "Sesuai Dengan Persyaratan Minimal", "Melebihi Persyaratan Minimal", " " }));

        cb_c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Tidak Berhubungan Dengan Pekerjaan", "Kurang Menunjang Pekerjaan", "Cukup Menunjang Pekerjaan", "Sesuai Kebutuhan Pekerjaan", "Melebihi Kebutuhan Pekerjaan" }));

        cb_c4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "1 Kegiatan/Jabatan", "2 Kegiatan/Jabatan", "3 Kegiatan/Jabatan", "4 Kegiatan/Jabatan", ">=5 Kegiatan/Jabatan" }));

        btn_laporan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/print30.png"))); // NOI18N
        btn_laporan.setText("Cetak");
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });

        cb_c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "< 20,00%", "20,00 < x 40,00 %", "40,00 < x 60,00 %", "60,00 < x 80,00%", "80,00 < x 100,00 %", " " }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus)
                        .addGap(268, 268, 268)
                        .addComponent(btn_laporan))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(txt_idKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_cari))
                                    .addComponent(txt_alternatif)))
                            .addComponent(jLabel4))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_c2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_c3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_c4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_c1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cb_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cb_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cb_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cb_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txt_idKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_alternatif, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_laporan))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TABEL PENILAIAN KARYAWAN");

        tb_penilaian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Karyawan", "Nama Karyawan", "Alternatif", "Tingkat Kehadiran", "Tingkat Pendidikan", "Pengembangan Diri", "Unsur Penunjang"
            }
        ));
        tb_penilaian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_penilaianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_penilaian);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );

        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private Connection setKoneksi() {
    try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/penilaian_karyawan","root","");
            stm=conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Koneksi Gagal :" +e);
        }
       return conn; 
    }
    
    private void tbl_penilaian() {
    Object header[]={"ID Karyawan","Nama Karyawan","Alternatif","Tingkat Kehadiran","Tingkat Pendidikan","Pengembangan Diri","Unsur Penunjang"};
    DefaultTableModel data=new DefaultTableModel(null,header);
    tb_penilaian.setModel(data);
    setKoneksi();
    String sql="select * from penilaian_alternatif";
    try{
        ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
                String kolom1=rs.getString("id_karyawan");
                String kolom2=rs.getString("nama_karyawan");
                String kolom3=rs.getString("alternatif");
                String kolom4=rs.getString("c1");
                String kolom5=rs.getString("c2");
                String kolom6=rs.getString("c3");
                String kolom7=rs.getString("c4");                
                
                String kolom[]={kolom1,kolom2,kolom3,kolom4,kolom5,kolom6,kolom7};
                data.addRow(kolom);
            }
    }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "data gagal dipanggil"+e);
        }
    }
    
    private void kosong() {
        txt_idKaryawan.setText("");
        txt_nama.setText("");
        txt_alternatif.setText("");
        cb_c1.setSelectedItem(0);
        cb_c2.setSelectedItem(0);
        cb_c3.setSelectedItem(0);
        cb_c4.setSelectedItem(0);    
    }
    
    public void autoAlternatif() {
        try {
            ResultSet rs = stm.executeQuery("SELECT * FROM penilaian_alternatif ORDER BY alternatif DESC");

            if (rs.next()) {
                int lastID = Integer.parseInt(rs.getString("alternatif").substring(1));
                int newID = lastID + 1;
                String AN = String.format("%d", newID);
                txt_alternatif.setText("A" + AN);
            } else {
                txt_alternatif.setText("A1");
            }
        } catch (Exception e) {
            txt_alternatif.setText("A1");
        }
    }
    
    private void btn_datakaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datakaryawanActionPerformed
        // TODO add your handling code here:
        new DataKaryawan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_datakaryawanActionPerformed

    private void btn_databobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_databobotActionPerformed
        // TODO add your handling code here:
        new DataBobot().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_databobotActionPerformed

    private void btn_penilaiankaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penilaiankaryawanActionPerformed
        // TODO add your handling code here:
        new PenilaianKaryawan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_penilaiankaryawanActionPerformed

    private void btn_prosesdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesdataActionPerformed
        // TODO add your handling code here:
        new ProsesData().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_prosesdataActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:\
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Simpan Data?", "Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0) {
        String sql = "insert into penilaian_alternatif values (?,?,?,?,?,?,?)";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, txt_idKaryawan.getText());
                stat.setString(2, txt_nama.getText());
                stat.setString(3, txt_alternatif.getText());

                String cbC1Value = cb_c1.getSelectedItem().toString();
                int nilaiC1 = 1;

                if (cbC1Value.equals("< 20,00%")) {
                    nilaiC1 = 20;
                } else if (cbC1Value.equals("20,00 < x 40,00 %")) {
                    nilaiC1 = 40;
                } else if (cbC1Value.equals("40,00 < x 60,00 %")) {
                    nilaiC1 = 60;
                } else if (cbC1Value.equals("60,00 < x 80,00%")) {
                    nilaiC1 = 80;
                } else if (cbC1Value.equals("80,00 < x 100,00 %")) {
                    nilaiC1 = 100;
                }
                stat.setString(4, String.valueOf(nilaiC1));

                String cbC2Value = cb_c2.getSelectedItem().toString();
                int nilaiC2 = 1;

                if (cbC2Value.equals("Kurang Dari Persyaratan Minimal")) {
                    nilaiC2 = 50;
                } else if (cbC2Value.equals("Sesuai Dengan Persyaratan Minimal")) {
                    nilaiC2 = 75;
                } else if (cbC2Value.equals("Melebihi Persyaratan Minimal")) {
                    nilaiC2 = 100;
                } 

                stat.setString(5, String.valueOf(nilaiC2));

                String cbC3Value = cb_c3.getSelectedItem().toString();
                int nilaiC3 = 1;

                if (cbC3Value.equals("Tidak Berhubungan Dengan Pekerjaan")) {
                    nilaiC3 = 20;
                } else if (cbC3Value.equals("Kurang Menunjang Pekerjaan")) {
                    nilaiC3 = 40;
                } else if (cbC3Value.equals("Cukup Menunjang Pekerjaan")) {
                    nilaiC3 = 60;
                } else if (cbC3Value.equals("Sesuai Kebutuhan Pekerjaan")) {
                    nilaiC3 = 80;
                } else if (cbC3Value.equals("Melebihi Kebutuhan Pekerjaan")) {
                    nilaiC3 = 100;
                }

                stat.setString(6, String.valueOf(nilaiC3));

                String cbC4Value = cb_c4.getSelectedItem().toString();
                int nilaiC4 = 1;

                if (cbC4Value.equals("1 Kegiatan/Jabatan")) {
                    nilaiC4 = 20;
                } else if (cbC4Value.equals("2 Kegiatan/Jabatan")) {
                    nilaiC4 = 40;
                } else if (cbC4Value.equals("3 Kegiatan/Jabatan")) {
                    nilaiC4 = 60;
                } else if (cbC4Value.equals("4 Kegiatan/Jabatan")) {
                    nilaiC4 = 80;
                } else if (cbC4Value.equals(">=5 Kegiatan/Jabatan")) {
                    nilaiC4 = 100;
                }

                stat.setString(7, String.valueOf(nilaiC4));

                stat.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data akan disimpan");
                kosong();
                txt_alternatif.requestFocus();
                tbl_penilaian();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "Data gagal disimpan" + e);
                tbl_penilaian();
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Ubah Data?", "Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0) {
            try {
                String sql = "update penilaian_alternatif set "
                        + "id_karyawan=?, "
                        + "nama_karyawan=?, "
                        + "alternatif=?, "
                        + "c1=?, "
                        + "c2=?, "
                        + "c3=?, "
                        + "c4=? "
                        + "where alternatif=?";

                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, txt_idKaryawan.getText());
                stat.setString(2, txt_nama.getText());
                stat.setString(3, txt_alternatif.getText());

                String cbC1Value = cb_c1.getSelectedItem().toString();
                int nilaiC1 = 1;

                if (cbC1Value.equals("< 20,00%")) {
                    nilaiC1 = 20;
                } else if (cbC1Value.equals("20,00 < x 40,00 %")) {
                    nilaiC1 = 40;
                } else if (cbC1Value.equals("40,00 < x 60,00 %")) {
                    nilaiC1 = 60;
                } else if (cbC1Value.equals("60,00 < x 80,00%")) {
                    nilaiC1 = 80;
                } else if (cbC1Value.equals("80,00 < x 100,00 %")) {
                    nilaiC1 = 100;
                }

                stat.setString(4, String.valueOf(nilaiC1));

                String cbC2Value = cb_c2.getSelectedItem().toString();
                int nilaiC2 = 1;

                if (cbC2Value.equals("Kurang Dari Persyaratan Minimal")) {
                    nilaiC2 = 50;
                } else if (cbC2Value.equals("Sesuai Dengan Persyaratan Minimal")) {
                    nilaiC2 = 75;
                } else if (cbC2Value.equals("Melebihi Persyaratan Minimal")) {
                    nilaiC2 = 100;
                } 

                stat.setString(5, String.valueOf(nilaiC2));

                String cbC3Value = cb_c3.getSelectedItem().toString();
                int nilaiC3 = 1;

                if (cbC3Value.equals("Tidak Berhubungan Dengan Pekerjaan")) {
                    nilaiC3 = 20;
                } else if (cbC3Value.equals("Kurang Menunjang Pekerjaan")) {
                    nilaiC3 = 40;
                } else if (cbC3Value.equals("Cukup Menunjang Pekerjaan")) {
                    nilaiC3 = 60;
                } else if (cbC3Value.equals("Sesuai Kebutuhan Pekerjaan")) {
                    nilaiC3 = 80;
                } else if (cbC3Value.equals("Melebihi Kebutuhan Pekerjaan")) {
                    nilaiC3 = 100;
                }

                stat.setString(6, String.valueOf(nilaiC3));

                String cbC4Value = cb_c4.getSelectedItem().toString();
                int nilaiC4 = 1;

               if (cbC4Value.equals("1 Kegiatan/Jabatan")) {
                    nilaiC4 = 20;
                } else if (cbC4Value.equals("2 Kegiatan/Jabatan")) {
                    nilaiC4 = 40;
                } else if (cbC4Value.equals("3 Kegiatan/Jabatan")) {
                    nilaiC4 = 60;
                } else if (cbC4Value.equals("4 Kegiatan/Jabatan")) {
                    nilaiC4 = 80;
                } else if (cbC4Value.equals(">=5 Kegiatan/Jabatan")) {
                    nilaiC4 = 100;
                }

                stat.setString(7, String.valueOf(nilaiC4));
                stat.setString(8, txt_alternatif.getText());

                stat.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data Akan Diubah");
                kosong();
                txt_idKaryawan.requestFocus();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "Data Gagal Diubah" + e);
            }
        tbl_penilaian();
    }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        kosong();
        tbl_penilaian();
        autoAlternatif();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(rootPane,"Hapus data ini?","Konfirmasi",JOptionPane.YES_NO_OPTION);
         if (ok==0){
             String sql = "delete from penilaian_alternatif where alternatif ='"+txt_alternatif.getText()+"'";
             try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data akan di hapus dari sistem?");
                kosong();
                txt_alternatif.requestFocus();
             }
                catch (SQLException e){
                JOptionPane.showMessageDialog(rootPane, "data gagal dihapus"+e);
             }
         tbl_penilaian();
         }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        PanelDataKaryawan PDK = new PanelDataKaryawan(this);
        jDesktopPane1.add(PDK);
        PDK.setVisible(true);
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        // TODO add your handling code here:
       JasperReport reports;

        String path=".\\src\\Tampilan\\Penilaian_Karyawan.jasper";
            try {
                
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
            System.out.println("Masuk try");
            
            } catch (JRException ex) {
                Logger.getLogger(PenilaianKaryawan.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void tb_penilaianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_penilaianMouseClicked
        // TODO add your handling code here:
        int baris = tb_penilaian.getSelectedRow();
        txt_idKaryawan.setText(tb_penilaian.getModel().getValueAt(baris, 0).toString());
        txt_nama.setText(tb_penilaian.getModel().getValueAt(baris, 1).toString());
        txt_alternatif.setText(tb_penilaian.getModel().getValueAt(baris, 2).toString());
        cb_c1.setSelectedItem(tb_penilaian.getModel().getValueAt(baris, 3).toString());
        cb_c2.setSelectedItem(tb_penilaian.getModel().getValueAt(baris, 4).toString());
        cb_c3.setSelectedItem(tb_penilaian.getModel().getValueAt(baris, 5).toString());
        cb_c4.setSelectedItem(tb_penilaian.getModel().getValueAt(baris, 6).toString());
    }//GEN-LAST:event_tb_penilaianMouseClicked

    private void btn_halamanutamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_halamanutamaActionPerformed
        // TODO add your handling code here:
        new HalamanUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_halamanutamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenilaianKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenilaianKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenilaianKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenilaianKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenilaianKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_databobot;
    private javax.swing.JButton btn_datakaryawan;
    private javax.swing.JButton btn_halamanutama;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_penilaiankaryawan;
    private javax.swing.JButton btn_prosesdata;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox<String> cb_c1;
    private javax.swing.JComboBox<String> cb_c2;
    private javax.swing.JComboBox<String> cb_c3;
    private javax.swing.JComboBox<String> cb_c4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tb_penilaian;
    private javax.swing.JTextField txt_alternatif;
    public javax.swing.JTextField txt_idKaryawan;
    public javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}
